version: '3.9'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'sticky'
      MONGO_INITDB_ROOT_PASSWORD: '123456'
    ports:
      - 27017:27017
